<!--
        This template shows a SSO box on the customer frontend pages
        Use this if you want to show a sso button on your frontend pages
    -->
<?php
$currentWebsiteId = $this->getCurrentWebsite();
$allIdpConfig = $this->getAllIdpConfiguration();
$websiteIds = $this->getWebsiteIds();
$selectedWebsites = $this->spUtility->isBlank($websiteIds) ? array() : json_decode($websiteIds);
if (!$this->spUtility->isBlank($selectedWebsites))
    foreach ($selectedWebsites as $key => $website) {
        if ($currentWebsiteId == $key) {
            foreach ($allIdpConfig as $item) {
                if ($item->getData()["show_customer_link"] == 1) {
                    print_r('
            <div style="text-align:left;width:100%;">
                <svg height="5" width="215">
                    <line x1="0" y1="0" x2="210" y2="0" style="stroke:#969393;stroke-width:3">
                </svg>OR
                <svg height="5" width="210">
                    <line x1="0" y1="0" x2="210" y2="0" style="stroke:#969393;stroke-width:3">
                </svg>
                <div class="card" style="margin-top:1%;">
                    <div class="primary">
                        <a href="' . $this->getSPInitiatedUrl(null, $item->getData()['idp_name']) . '" class="action login primary" style="padding: 1% 14%;">
                            <span>Login with ' . $item->getData()['idp_name'] . '</span>
                        </a>
                    </div>
                </div>
            </div>');
                }
            }

        }

    }
