<script>
    require(['Magento_Customer/js/customer-data'], function ($) {
        $.reload(['customer', 'compare-products', 'last-ordered-items', 'cart']);
    });

    function mo_invalidate($, fullname, fistname) {
        $('.greet.welcome').html('<span data-bind="text: new String(\'Welcome, %1!\').replace(\'%1\', customer().firstname)">Welcome, ' + fistname + '!</span>');
        $('.customer-name span').html(fullname);
    }
</script>

<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if ($customerSession->isLoggedIn()) {

    $fullname = $customerSession->getCustomer()->getName();
    $fname = $customerSession->getCustomer()->getFirstname();
    if (!empty($fullname)) {

        ?>
        <script>
            require(function ($, script) {

                $(window).load(function () {

                    var delay = 0;
                    while (delay < 5000) {
                        setTimeout(function () {
                            mo_invalidate($, "<?php print_r($fullname);?>", "<?php print_r($fname);?>");
                        }, delay);
                        delay += 100;
                    }

                });


            });
        </script>

        <?php

    }
}


?>
