<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

$logger = $objectManager->get("Psr\Log\LoggerInterface");

if (!$customerSession->isLoggedIn()) {
    $params = $this->getRequest()->getParams(); //get params
    $checkbackdoorurl = !empty($params['saml_sso']) ? $params['saml_sso'] : 1;
    if ($this->isAllPageAutoRedirectEnabled_action() && $this->isSiteEnable()) {
        $logger->debug("Customer not logged in: Redirecting To IDP");
        $currentUrl = $this->getCurrentUrl();
        $logger->debug("CurrentURL: " . $currentUrl);
        $redirect = $objectManager->get('\Magento\Framework\App\Response\Http');
        $autoredirect_appName = $this->getAutoRedirect_AppName();

        $redirect->setRedirect($this->getSPInitiatedUrl($currentUrl) . $autoredirect_appName);
    }

}

?>
