<!--
        This template shows a SSO box on the admin backend pages
        Use this if you want to show a sso button on your backend pages
    -->
<?php
$allIdpConfig = $this->getAllIdpConfiguration();

foreach ($allIdpConfig as $item) {
    if ($item->getData()["show_admin_link"] == 1) {
        print_r('<div class="actions" style="text-align:center;">
            <svg height="5" width="131">
                <line x1="0" y1="0" x2="127" y2="0" style="stroke:#969393;stroke-width:3">
            </svg>OR
            <svg height="5" width="133">
                <line x1="0" y1="0" x2="128" y2="0" style="stroke:#969393;stroke-width:3">
            </svg>
            <a class="action-login action-primary" style="color:white;text-decoration:none;" href="' . $this->getSPInitiatedUrl(null, $item->getData()['idp_name']) . '">
                Login with ' . $item->getData()['idp_name'] . '
            </a>
    </div>');
    }
}
