<!--
    This template file is for the SAML Attribute/Role Mapping settings.
    File acts as a view file for our attribute / role mapping page.
-->

<?php
/**
 * Attribute mapping
 * initialize all values required to be shown on the page
 */

$roles = $this->getAllRoles();
$groups = $this->getAllGroups();

$isEnabled = $this->isEnabled();

$collection = $this->getAllIdpConfiguration();
$default_provider = $this->getProvider();
$idpDetails = null;
$count = 0;
foreach ($collection as $item) {
    $count++;
    if ($item->getData()["idp_name"] === $default_provider) {
        $idpDetails = $item->getData();
    }
}
if (empty($idpDetails)) {
    foreach ($collection as $item) {
        $idpDetails = $item->getData();
        break;
    }
    if (isset($idpDetails['idp_name'])) {
        $default_provider = $idpDetails['idp_name'];
    }
}
$disabled = !$isEnabled || $count == 0 ? "disabled" : "";
if ($this->isTrialExpired()) {
    $disabled = "disabled";
}
$saml_am_account_matcher = $this->getAccountMatcher();

$emailSelected = !empty($idpDetails['create_magento_account_by']) && $idpDetails['create_magento_account_by'] == 'email' ? 'selected="selected"' : "";
$usernameSelected = !empty($idpDetails['create_magento_account_by']) && $idpDetails['create_magento_account_by'] == 'username' ? 'selected="selected"' : "";
$saml_am_username = !empty($idpDetails) ? $idpDetails['username_attribute'] : '';
$saml_am_email = !empty($idpDetails) ? $idpDetails['email_attribute'] : '';

$saml_am_first_name = !empty($idpDetails) ? $idpDetails['firstname_attribute'] : '';
$saml_am_last_name = !empty($idpDetails) ? $idpDetails['lastname_attribute'] : '';
$saml_am_group_name = !empty($idpDetails) ? $idpDetails['group_attribute'] : '';

$saml_am_country_billing = !empty($idpDetails) ? $idpDetails['billing_country_attribute'] : '';
$saml_am_city_billing = !empty($idpDetails) ? $idpDetails['billing_city_attribute'] : '';
$saml_am_address_billing = !empty($idpDetails) ? $idpDetails['billing_address_attribute'] : '';
$saml_am_phone_billing = !empty($idpDetails) ? $idpDetails['billing_phone_attribute'] : '';
$saml_am_state_billing = !empty($idpDetails) ? $idpDetails['billing_state_attribute'] : '';
$saml_am_zipcode_billing = !empty($idpDetails) ? $idpDetails['billing_zip_attribute'] : '';

$saml_am_country_shipping = !empty($idpDetails) ? $idpDetails['shipping_country_attribute'] : '';
$saml_am_city_shipping = !empty($idpDetails) ? $idpDetails['shipping_city_attribute'] : '';
$saml_am_address_shipping = !empty($idpDetails) ? $idpDetails['shipping_address_attribute'] : '';
$saml_am_phone_shipping = !empty($idpDetails) ? $idpDetails['shipping_phone_attribute'] : '';
$saml_am_state_shipping = !empty($idpDetails) ? $idpDetails['shipping_state_attribute'] : '';
$saml_am_zipcode_shipping = !empty($idpDetails) ? $idpDetails['shipping_zip_attribute'] : '';

$billinandshippingchcekbox = !empty($idpDetails) ? $idpDetails['saml_enable_billingandshipping'] : '';
$sameasbilling = !empty($idpDetails) ? $idpDetails['saml_sameasbilling'] : '';
$customAttribute = !empty($idpDetails) ? (array)json_decode($idpDetails['custom_attributes']) : array();
$customs = $customAttribute;

$saml_am_update_attribute = !empty($idpDetails) ? $idpDetails['update_attributes_on_login'] : '';

$formKey = $this->getBlockHtml('formkey');
$plantype = !$this->check_license_plan(2) ? 'disabled' : '';
$premiumlink = $this->getExtensionPageUrl('upgrade');


echo '
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<div class="row">
<div class="col-sm-8">
<div class="page" id="attrmapping">
        <div class="mosp_table_layout">
        ';
if ($this->check_license_plan(3)) {
    echo '
            <form name="f" method="post" action="">
                ' . $formKey . '
                <input type="hidden" name="option" value="saveProvider">
            <tr>
                <td><strong>Identity Provider:</strong></td>
                <td>
                 <select onchange="this.form.submit()" id="mo_identity_provider" ' . $disabled . '  name="mo_identity_provider"
                 style="width:auto;">';

    foreach ($collection as $item) {
        $selected = $default_provider == $item->getData()["idp_name"] ? 'selected' : '';
        print_r('<option id="mo2f_roles" ' . $selected . '
                            name="' . $item->getData()["idp_name"] . '" value="' . $item->getData()["idp_name"] . '">' .
            $item->getData()["idp_name"] . '</option>');
    }
    echo '
                            </select>
                            <i>Select Identity Provider to configure Attribute Mapping.</i>
                    </td>
            </tr>
            </form>
            ';
}
echo '

            <br>
            <form name="f" method="post" action="">
                ' . $formKey . '
                <input type="hidden" name="option" value="saveAttrSettings" />
                <input type="hidden" name="mo_identity_provider" value="' . $default_provider . '">
                <h3>Attribute Mapping (Optional)';
echo (!$this->check_license_plan(2)) ? '<small style="color:red; font-weight: bold; font-size: 1.4rem;"><a style="color:red; " href="' . $premiumlink . '"
                class="premium premium-btn-link">[PREMIUM]</a></small>' : '';
echo '</h3><hr>
                <table>
                    <tr>
                        <td colspan="2">
                            <div class="mo_note">
                                <span class="btn-link">What is Attribute Mapping?</span>
                                <div hidden class="collapse">
                                    <ol>
                                        <li>Attributes are user details that are stored in your Identity Provider.</li>
                                        <li>Attribute Mapping helps you to get user attributes from your IdP and map them to
                                            Magento user attributes like firstname, lastname etc.</li>
                                        <li>While auto registering the users in your Magento site these attributes will automatically
                                            get mapped to your Magento user details.</li>
                                    </ol>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"><b>NOTE: </b>Use attribute name <code>NameID</code> if Identity is in the
                            <i>NameIdentifier</i> element of the subject statement in SAML Response.</td>
                    </tr>
                    <tr><td colspan="2"><input type="checkbox" id="update_attribute"
                        name="saml_am_update_attribute" value="checked"
                        ' . $saml_am_update_attribute . ' ' . $disabled . ' ' . $plantype . ' >
                        &nbsp;&nbsp;Update Attribute. <span style="margin-left:451px;font-style: italic">(Email cannot be update)</span></td></tr>
                        <br>
                    <tr>
                        <td style="width:200px;"><strong>Login/Create Magento account by: </strong></td>
                        <td><select name="saml_am_account_matcher" id="saml_am_account_matcher" ' . $disabled . ' ' . $plantype . '>
                            <option value="email" ' . $emailSelected . ' > Email </option>
                            <option value="username" ' . $usernameSelected . ' > Username </option>
                        </select>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td><i>Users in Magento will be searched (existing Magento users) or created (new users) based on this
                            attribute. Use Email by default.</i></td>
                    </tr>
                    <tr>
                        <td style="width:150px;"><strong>Username <span style="color:red;">*</span>:</strong></td>
                        <td><input type="text" name="saml_am_username" placeholder="Enter attribute name for Username"
                            value="' . $saml_am_username . '" required ' . $disabled . ' ' . $plantype . '/></td>
                    </tr>
                    <tr>
                        <td><strong>Email <span style="color:red;">*</span>:</strong></td>
                        <td><input type="text" name="saml_am_email" placeholder="Enter attribute name for Email"
                            value="' . $saml_am_email . '" required ' . $disabled . ' ' . $plantype . '/></td>
                    </tr>
                    <tr>
                        <td><strong>First Name:</strong></td>
                        <td><input type="text" name="saml_am_first_name" placeholder="Enter attribute name for First Name"
                            value="' . $saml_am_first_name . '" ' . $disabled . ' ' . $plantype . '/></td>
                    </tr>
                    <tr>
                        <td><strong>Last Name:</strong></td>
                        <td><input type="text" name="saml_am_last_name" placeholder="Enter attribute name for Last Name"
                            value="' . $saml_am_last_name . '" ' . $disabled . ' ' . $plantype . '/></td>
                    </tr>
                    <tr>
                        <td><strong>Group/Role:</strong></td>
                        <td><input type="text" name="saml_am_group_name" placeholder="Enter attribute name for Group/Role"
                            value="' . $saml_am_group_name . '" ' . $disabled . ' ' . $plantype . '/></td>
                    </tr>

                    <tr for="chkSelect">
                            <td colspan="2"><input type="checkbox" name= "saml_am_billingandshipping" value="checked" id="chkSelect" style="width=100px" ' . $billinandshippingchcekbox . ' ' . $disabled . ' ' . $plantype . '/>
                                    <strong>Map Billing/Shipping Address</strong>

                             <div class="custom-select" id="content" style="display:' . $billinandshippingchcekbox . '">
                             <hr />
                             <div class="container">
                             <div class="row">
                               <div class="col-sm-4">

                                <h3 class="text-primary">Map Billing Address Attribute</h3>

                                  <br>
                                <!--=== Billing address=== -->
                                <table>
                                 <tr class="form-group">
                                    <td><strong>Street Adress:</strong></td>
                                    <td><input type="text" name="saml_am_address_billing" class="address_textboxes"
                                    placeholder="Address" id="pAddress" value="' . $saml_am_address_billing . '" ' . $disabled . ' ' . $plantype . '/></td>
                                 </tr>

                                  <tr class="form-group">
                                  <td><strong>Zip Code:</strong></td>
                                     <td> <input type="text" name="saml_am_zipcode_billing" class="address_textboxes"
                                     placeholder="Zip Code" id="pZipcode" value="' . $saml_am_zipcode_billing . '" ' . $disabled . ' ' . $plantype . '/></td>
                                   </tr>

                                  <tr class="form-group">
                                  <td><strong>City Name:</strong></td>
                                    <td><input type="text" name="saml_am_city_billing" class="address_textboxes"
                                     placeholder="City" id="pCity" value="' . $saml_am_city_billing . '" ' . $disabled . ' ' . $plantype . '/></td>
                                   </tr>

                                  <tr class="form-group">
                                      <td><strong>State:</strong></td>
                                      <td><input type="text" name="saml_am_state_billing" class="address_textboxes"
                                      placeholder="State" id="pState" value="' . $saml_am_state_billing . '" ' . $disabled . ' ' . $plantype . '/></td>
                                   </tr>

                                   <tr class="form-group">
                                      <td><strong>Country Name:</strong></td>
                                      <td><input type="text" name="saml_am_country_billing" class="address_textboxes"
                                      placeholder="country" id="pCountry" value="' . $saml_am_country_billing . '" ' . $disabled . ' ' . $plantype . '/></td>
                                    </tr>

                                    <tr class="form-group">
                                    <td><strong>Telephone:</strong></td>
                                      <td><input type="text" name="saml_am_phone_billing" class="address_textboxes"
                                      placeholder="Telephone" id="pTelephone" value="' . $saml_am_phone_billing . '" ' . $disabled . ' ' . $plantype . '/></td>
                                    </tr>
                                <!--=== Shipping address=== -->
                                </table>
                               </div>
                               <div class="col-sm-4">


                               <h3 class="text-primary">Map Shipping Address Attribute</h3>

                                   <div class="form-group">
                                      <input type="checkbox" name ="saml_am_sameasbilling" value="checked" id="checkBox"  onclick="FillAddressInput()"  ' . $sameasbilling . ' ' . $disabled . '> Same as billing address
                                   </div>

                                <!--=== current address=== -->
                            <table>
                                  <tr class="form-group">
                                     <td><strong>Street Adress:</strong></td>
                                      <td><input type="text" name="saml_am_address_shipping" class="address_textboxes"
                                      placeholder="Address" id="curAddress" value="' . $saml_am_address_shipping . '" ' . $disabled . ' ' . $plantype . '/></td>
                                   </tr>


                                  <tr class="form-group">
                                  <td><strong>Zip Code:</strong></td>
                                    <td><input type="text" name="saml_am_zipcode_shipping" class="address_textboxes"
                                    placeholder="Zip Code" id="curZipcode" value="' . $saml_am_zipcode_shipping . '" ' . $disabled . ' ' . $plantype . '/></td>
                                   </tr>

                                  <tr class="form-group">
                                      <td><strong>City Name:</strong></td>
                                      <td><input type="text" name="saml_am_city_shipping" class="address_textboxes"
                                      placeholder="City" id="curCity" value="' . $saml_am_city_shipping . '" ' . $disabled . ' ' . $plantype . '/></td>
                                   </tr>

                                  <tr class="form-group">
                                      <td><strong>State:</strong></td>
                                      <td><input type="text" name="saml_am_state_shipping" class="address_textboxes"
                                      placeholder="State" id="curState" value="' . $saml_am_state_shipping . '" ' . $disabled . ' ' . $plantype . '/></td>
                                   </tr>

                                  <tr class="form-group">
                                      <td><strong>Country Name:</strong></td>
                                      <td><input type="text" name="saml_am_country_shipping" class="address_textboxes"
                                      placeholder="country" id="curCountry" value="' . $saml_am_country_shipping . '" ' . $disabled . ' ' . $plantype . '/></td>
                                   </tr>

                                   <tr class="form-group">
                                    <td><strong>Telephone:</strong></td>
                                      <td><input type="text" name="saml_am_phone_shipping" class="address_textboxes"
                                      placeholder="Telephone" id="curTelephone" value="' . $saml_am_phone_shipping . '" ' . $disabled . ' ' . $plantype . '/></td>
                                    </tr>

                                <!--=== current address=== -->
                            </table>
                               </div>
                               <div class="col-sm-4"></div>
                            </div>
                            </div>
                            </td>
                    </tr>

                    <tr>
                        <td>&nbsp;</td>
                        <td><br /><input type="submit" style="width:120px;" name="submit" value="Save"
                            class=" btn-round" ' . $disabled . ' ' . $plantype . '/> &nbsp;
                        <br /><br />
                        </td>
                    </tr>
                </table>

                <h3>Custom Mapping</h3><hr/>
         <div>
           <div class="form-group same-row hmargin">
               <label for="this_attribute"><b>Enter Attribute Name: </b></label>
           </div>
           <div class="form-group same-row hmargin">
               <input class="form-control gm-input" ' . $disabled . ' ' . $plantype . ' style="margin-left:14%; width:216%" {log} id="this_attribute" name="this_attribute" type="text" placeholder="Please enter code of your Custom Attribute" value = "">
           </div>
           <div class="form-group same-row hmargin" style = "margin-left:26.5%">
               <button class="btn-round" type="button"  ' . $disabled . ' ' . $plantype . ' {log} onClick="addCustomAttribute()">Add (+)</button>
           </div>
           <div class="form-group same-row hmargin">
               <button class="btn-round" type="button" ' . $disabled . ' ' . $plantype . ' {log} onClick="deleteCustomAttribute()">Delete (-)</button>
           </div>
        </div>
        <div style="text:inline;" class="new-row vmargin">';
$custom_maps = array();
foreach ($customs as $key => $value) {
    $custom_value = $value;
    $custom_key = $key;
    if (empty($customAttribute)) {
        !empty($custom_maps[$custom_value]) ? $custom_maps[$custom_value] : "";
    } else {
        $custom_maps = $customAttribute;
        $value = !empty($custom_maps[$custom_value]) ? $custom_maps[$custom_value] : "";
    }
    echo '<div style="padding:3px; margin-left:9px;" id ="' . $custom_key . 'Div" class="gm-div same-row ">
                                  <td><strong>' . $custom_key . ':</strong></td>
                                  <td>
                                  <input class="form-control gm-input" style="margin-left:200px; width:370px; position:absolute" {log} id="' . $custom_key . '" name="' . $custom_key . '" type="text" value="' . $custom_value . '"> </td>
                             </div>';

}


echo '      <div id="submit_custom_attr" class="form-group center">
                            <br>
                            <input type="submit" name="submit" value="Save" style="width:120px; margin-left: -340px" class="btn-round" ' . $disabled . ' ' . $plantype . '/> &nbsp;
                            <br>
                         </div>

        </div>
  </form>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#chkSelect").click(function () {
                if ($(this).is(":checked")) {
                    $("#content").show();
                } else {
                    $("#content").hide();
                }
            });
        });

    function FillAddressInput()
    {
       let checkBox= document.getElementById("checkBox");

       let pAddress = document.getElementById("pAddress");
       let pZipcode = document.getElementById("pZipcode");
       let pCity = document.getElementById("pCity");
       let pState = document.getElementById("pState");
       let pCountry = document.getElementById("pCountry");
       let pTelephone = document.getElementById("pTelephone");

       let curAddress = document.getElementById("curAddress");
       let curZipcode = document.getElementById("curZipcode");
       let curCity = document.getElementById("curCity");
       let curState = document.getElementById("curState");
       let curCountry = document.getElementById("curCountry");
       let curTelephone = document.getElementById("curTelephone");

        if (checkBox.checked == true)
        {

       let pAddressValue      = pAddress.value;
       let pZipcodeValue      = pZipcode.value;
       let pCityValue         = pCity.value;
       let pStateValue        = pState.value;
       let pCountryValue      = pCountry.value;
       let pTelephoneValue    = pTelephone.value;


       curAddress.value      = pAddressValue;
       curZipcode.value      = pZipcodeValue;
       curCity.value         = pCityValue;
       curState.value        = pStateValue;
       curCountry.value      = pCountryValue;
       curTelephone.value    = pTelephoneValue;



       }
        else
        {
       curAddress.value = "";
       curZipcode.value      = "";
       curCity.value         = "";
       curState.value        = "";
       curCountry.value      = "";
       curTelephone.value    = "";      }
    }
    </script>
';

