<!--
    This template file is for the Sign In settings.
    File acts as a view file for our Sign In settings.
-->
<?php
// initialize all values
$isEnabled = $this->isEnabled();
$disabled = !$isEnabled ? "disabled" : "";
if ($this->isTrialExpired()) {
    $disabled = "disabled";
}
$formKey = $this->getBlockHtml('formkey');
$allIdpConfig = $this->getAllIdpConfiguration();
$spInitiatedUrl = $this->getBaseUrl() . "mospsaml/actions/sendAuthnRequest";
$spsettings = $this->getExtensionPageUrl('spsettings');

$testUrl = !empty($idp_name) ? $this->getTestUrl($idp_name) : '';


?>
<script>
    var testURL = "'.$testUrl.'";
</script>
<div class="page" id="identityproviders">
    <div class="mosp_table_layout">

        <form method="post" id="add-identity-provider-form" action="<?php echo $spsettings ?>">
            <?php echo $formKey; ?>
            <input id="" type="hidden" name="add" value="add">
            <input type="submit" <?php echo $disabled; ?> value="Add Provider"
                   style="width:150px; margin-right:3%; float:right" class="btn btn-small btn-danger btn-round"></form>

        <form id="identityProviders_form" method="post" action="">
            <h3>List Of Identity Providers &nbsp &nbsp &nbsp &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp &nbsp &nbsp &nbsp
                &nbsp&nbsp &nbsp&nbsp &nbsp&nbsp &nbsp
            </h3>

            <table class="table table-striped table-hover table-bordered" id="idp_list_table" style="width: 99%;">
                <thead>
                <tr>
                    <th width="10%">Identity Provider Name</th>
                    <th width="20%">SSO Link</th>
                    <th width="10%">Actions</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <td colspan="6">
                    </td>
                </tr>
                </tfoot>
                <tbody>

                <?php foreach ($allIdpConfig

                as $item) { ?>
                <tr>
                    <td><?php echo $item->getData()['idp_name']; ?> </td>
                    <td><?php echo $spInitiatedUrl . "?idp_name=" . $item->getData()['idp_name']; ?></td>
                    <td class="center-btn">
                        <table>
                            <tr>
                            <tr>
                                <td>
                                    <form method="post" id="idp-delete-form" action="">
                                        <?php echo $formKey; ?>
                                        <input id="" type="hidden" name="id"
                                               value="<?php echo $item->getData()['id']; ?>">
                                        <input id="" type="hidden" name="delete" value="delete">
                                        <input type="submit" value="Delete" <?php echo $disabled; ?>
                                               style="width:50%;margin-left:40%;"
                                               class="btn btn-small btn-danger btn-round"></form>
                                </td>
                                <td>
                                    <form method="post" id="idp-edit-form"
                                          action="<?php echo $spsettings . '&idp_name=' . $item->getData()['idp_name'] ?>">
                                        <?php echo $formKey; ?>
                                        <input id="" type="hidden" name="idp_name"
                                               value="<?php echo $item->getData()['idp_name']; ?>">
                                        <input id="" type="hidden" name="edit" value="edit">
                                        <input type="submit" value="Edit" <?php echo $disabled; ?>
                                               style="width:133%;margin-left:-50%;"
                                               class="btn btn-small btn-danger btn-round"></form>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <form method="post" id="idp-test-form" action="">
                                        <?php echo $formKey; ?>
                                        <input id="" type="hidden" name="idp_name"
                                               value="<?php echo $item->getData()['idp_name']; ?>">
                                        <input class="btn-round idp_test_btn" type="button" name="test" id="test"
                                               title="You can only test your Configuration after saving your Service Provider Settings."
                                               href="#"
                                               onclick="submitForm('<?php echo $this->getTestUrl($item->getData()['idp_name']) ?>');" <?php echo $disabled; ?>
                                               style="width:150px;margin-left:40%;margin-top:-15%" <?php echo $isEnabled; ?>
                                               value="Test configuration">
                                    </form>
                                </td>
                            </tr>
                            &nbsp

                            </tr>
                        </table>
                    </td>
            </tr>
        </form>
            <?php } ?>

            </tbody></table>
    </div>
