<!--
    This template file is for the SAML Identity Provider settings.
    File acts as a view file for our Identity Provider settings.
-->

<?php
// initialize all values required on the page
$isserUrl = $this->getIssuerUrl();
$baseUrl = $this->getBaseUrl();
$publicCert = $this->getPublicCert();
$isEnabled = $this->isEnabled();
$acsUrl = $this->getAcsUrl();
$sloUrl = $this->getssourl();
$metadataurl = $this->getMetadataUrl();
$formKey = $this->getBlockHtml('formkey');

echo '<div class="row">
<div class="col-sm-8">
<div class="page" id="identityprovider">
        <h3>CONFIGURE IDENTITY PROVIDER</h3><hr>
        <div id="idp-settings" class="mosp_table_layout">
            <h3><b>STEP 1:</b></h3>
            <p>
                <b>Choose your Identity Provider from the list below to download its setup guide:</b>
                <br/><br/>
                <select name="idpguide" id="idpguide" style="width:200px;">
                    <option value selected disabled>Select your IDP</option>
                    <option value="https://plugins.miniorange.com/saml-single-sign-on-sso-into-magento-using-azure-ad-idp">Azure AD</option>
                    <option value="https://plugins.miniorange.com/saml-single-sign-on-sso-magento-using-adfs-as-idp">ADFS</option>
                    <option value="https://plugins.miniorange.com/saml-single-sign-on-sso-magento-using-okta-as-idp">Okta</option>
                    <option value="https://plugins.miniorange.com/magento-single-sign-sso-using-google-apps-idp">Google Apps</option>
                    <option value="https://plugins.miniorange.com/saml-single-sign-on-sso-magento-using-salesforce-idp">Salesforce</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-miniorange-as-idp">miniOrange</option>
                    <option value="https://plugins.miniorange.com/magento-single-sign-on-sso-using-jboss-keycloak-idp">JBoss Keycloak</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-onelogin-as-idp">OneLogin</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-auth0-as-idp">Auth0</option>
                    <option value="https://plugins.miniorange.com/saml-single-sign-on-sso-magento-using-centrify">Centrify</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-oracle-enterprise-manager-as-idp">Oracle</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-shibboleth2-as-idp">Shibboleth 3</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-office-365-as-idp">Office 365</option>

                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-simplesaml-as-idp">SimpleSAML</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-bitium-as-idp">Bitium</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-pingfederate-as-idp">PingFederate</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-openam-as-idp">OpenAM</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-authanvil-as-idp">AuthAnvil</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-rsa-securid-as-idp">RSA SecurID</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-gluu-server-as-idp">Gluu Server</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-jumpcloud-as-idp">Jumpcloud</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-absorb-lms-as-idp">Absorb LMS</option>
                    <option value="https://plugins.miniorange.com/saml-single-sign-sso-magento-using-wso2">WSO2</option>
                    <option value="https://plugins.miniorange.com/magento-single-sign-on-sso-with-drupal">Drupal</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-wordpress-as-idp">Wordpress</option>
                    <option value="https://plugins.miniorange.com/magento-saml-single-sign-on-sso-using-joomla-as-idp">Joomla</option>
                    <option value="https://www.miniorange.com/contact">Other</option>
                </select>
                <a  class="button btn-round" style="font-size: 100%; margin-left: 1%;" href="" target="_blank" id="idpsetuplink" hidden >Click here for setup guide.</a>
            </p>
            <div class="code">Your IdP is not in the list? Scroll up and use the support section to contact us and we will help you set
                the module with your IDP.</div>
            <br>
            <h4>You will need the following information to configure your IdP. Copy it and keep it handy:</h4>
            <div style="padding:0 6% 0 0;">
                <table class="data center">
                    <tr>
                        <td><b>SP-EntityID / Issuer</b></td>
                        <td>' . $isserUrl . '</td>
                    </tr>
                    <tr>
                        <td><b>ACS (AssertionConsumerService) URL</b></td>
                        <td>' . $acsUrl . '</td>
                    </tr>
                    <tr>
                        <td><b>Single Logout URL</b></td>
                        <td>' . $sloUrl . '</td>
                    </tr>
                    <tr>
                        <td><b>Audience URI</b></td>
                        <td>' . $isserUrl . '</td>
                    </tr>
                    <tr>
                        <td><b>NameID format</b></td>
                        <td>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</td>
                    </tr>
                    <tr>
                        <td><b>Recipient URL</b></td>
                        <td>' . $baseUrl . '</td>
                    </tr>
                    <tr>
                        <td><b>Destination URL</b></td>
                        <td>' . $baseUrl . '</td>
                    </tr>
                    <tr>
                        <td><b>Default Relay State (Optional)</b></td>
                        <td>' . $baseUrl . '</td>
                    </tr>
                    <tr>
                        <td><b>Certificate (Optional)</b></td>';
if (!$isEnabled) {
    echo '                       <td padding: 15px;"><i>(Register to download the certificate)</i></td>';
} else {
    echo '                       <td padding: 15px;"><a href="' . $publicCert . '" >Download</a></td>';
}
echo '               </tr>
                </table>
                <br><br>
                <tr>
                        <td>
                        <strong>b) You can provide this metadata URL to your Service Provider:</strong>
                        </td>
                        <br>
                        <td>

                                    <div class="copy-link">
                                        <input type="text" name="metadata_url" class="copy-link-input" value="' . $metadataurl . '" readonly  required ' . $isEnabled . ' disabled>
                                        <button type="button" class="copy-link-button">
                                            <span class="material-icons" >
                                                <img  src="' . $this->getViewFileUrl('MiniOrange_SP::images/copy.png') . '" alt="copy" class="copy-img">
                                            </span>
                                            <span class="copy-text">copied</span>
                                      </button>
                                    </div>

                         </td>

                         <br><br>

           </tr>
            </div>

            <form name="f" method="post" action=""> ' . $formKey . '
           <input type="hidden" name="option" value="download_metadata" >
           <td>
           <strong>c) Download the Plugin XML metadata and upload it on your Service Provider:</strong>
           </td>
           <div style="text-align:left">
           <br>
           <input type="submit" name="metadata_file" value="Download XML Metadata"  class="btn-round"
           </div>

        </form>

            <br><br>
            <h3><b>STEP 2:</b></h3>
            <b>Assuming that you are now done with Step 1, please note down the following information from your IdP admin screen
                and keep it handy to configure your Service provider.</b>
            <div style="margin:2%;">
                <ol>
                    <li><b>X.509 certificate</b></li>
                    <li><b>SAML Login URL (Single Sign On URL)</b></li>
                    <li><b>IdP Entity ID (IdP Issuer)</b></li>
                    <li><b>Is Response signed</b> by your IdP?</li>
                    <li><b>Is Assertion signed</b> by your IdP?</li>
                    </li>
                </ol>
            </div>
            <div class="mo_note">
                <span class="btn-link"><i>Cannot find the above information?</i></span>
                <div hidden class="collapse">
                    <ol>
                        <li>X.509 certificate is enclosed in <code>X509Certificate</code> tag in IdP-Metadata XML file.
                                (parent tag: <code>KeyDescriptor use="signing"</code>)</li>
                        <li>SAML Login URL is enclosed in <code>SingleSignOnService</code> tag (Binding type: HTTP-Redirect) in
                            IdP-Metadata XML file.</li>
                        <li>EntityID is the value of the <code>entityID</code> attribute of <code>EntityDescriptor</code> tag
                            in IdP-Metadata XML file. </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>';
