<!--Multisite Tab-->
<?php
 $webstore= null;
 $websitelink= null;
 $websiteCount = 0;
 $websites=$this->getWebsiteCollection();
 $isEnabled = $this->isEnabled();
$disabled = !$isEnabled ? "disabled" : "";
if($this->isTrialExpired()){
	$disabled = "disabled";
}
 $formKey = $this->getBlockHtml('formkey');
 $allWebsites=array();
foreach($this->getWebsiteCollection() as $website) {
	$allWebsites[$website->getId()]=$website->getName();
	$showWebsite[$website->getId()] = $this->showWebsite($website->getId())==1 ?'checked':'';
	$allStores= $this->getStoreIds($website->getId());
	foreach($allStores as $stores)
	{
		$showStores[$this->getStoreName($stores)]=$this->showWebsite($website->getId())==1 ?'checked':'';
	}
	$websiteCount++;
}
	$showWebsite[$website->getId()] = $this->showWebsite($website->getId())==1 ?'checked':'';

echo' 
<form name="multisite" id="multisite" method="post" action="">
	  <input type="hidden" name="check_count" id="check_count" value="">
	  <input type="hidden" name="option" value="multisiteSettings" >
	  <input type="hidden" name="website_count" id="website_count" value='.$websiteCount.'';
foreach($this->getWebsiteCollection() as $website)
{
	$websiteId = $website->getId();

echo'
        '.$formKey.'
		<style>
			.hide {
		  	display: none;
			}

			.myDIV:hover + .hide {
		  	display: block;
		  	color: green;
			}
        	.tab {
            	display: inline-block;
            	margin-left: 40px;
        	}
    	</style>
		<input type="checkbox" '.$disabled.' name='.$websiteId.' '.$showWebsite[$websiteId].' id="check1_'.$websiteId.'"  class="check1" value="true" style="margin-left:15px"> <b style="margin-left:5px">'.$website->getName().'</b><br><br><br>

		';
	$allstores= $this->getStoreIds($websiteId);
}

echo '<tr><td>


		<td>
		<br>
			<input type="submit" class="btn-round" '.$disabled.' name="submit" style="width:100px;" value="Save" class="button button-primary button-large" onClick="afterClick()"/> &nbsp;
		</td>
	</form>
	<div class="row">
	<div class="col-sm-8">
<script>

	function afterClick()
	{
		var cont = jQuery(".check1:checkbox");
		var count=0;
		for (var i = 0; i < cont.length; i++) {
            if (cont[i].tagName == "INPUT" && cont[i].type == "checkbox") {
                if (cont[i].checked) {		
                    count++;
                }
            }
        }
		jQuery("#check_count").attr("value",count);
	}
</script>
';
