<?php

// initialize all variables
$spsettings = $this->getExtensionPageUrl('spsettings');
$idpsettings = $this->getExtensionPageUrl('idpsettings');
$idps = $this->getExtensionPageUrl('idps');
$count = $this->spUtility->getcounttable();
if ($count > 0 && $this->check_license_plan(3)) {
    $planName = 'Enterprise';
    $spsettings = $this->getExtensionPageUrl('idps');
}
$planName = $this->check_license_plan(3) ? 'Enterprise' : ($this->check_license_plan(2) ? 'Premium' : ($this->check_license_plan(1) ? 'Standard' : 'SSO'));
$account = $this->getExtensionPageUrl('account');
$signinsettings = $this->getExtensionPageUrl('signinsettings');
$attrsettings = $this->getExtensionPageUrl('attrsettings');
$rolesettings = $this->getExtensionPageUrl('rolesettings');
$multisitesettings = $this->getExtensionPageUrl('multisitesettings');
$support = $this->getExtensionPageUrl('support');
$pricing = $this->getExtensionPageUrl('upgrade');
$activeTab = $this->getCurrentActiveTab();
$is_trial_plan = $this->check_license_plan(4) ? 1 : 0;
$license = $this->chk_Premium();
if ($license != NULL) {
    $days = $this->check_license_expiry_date();
    if ($days <= 30) {
        echo '
           <div class="notice notice-warning">Your miniOrange Magento SAML SSO Plugin license is ';
        if ($days > 0) {
            echo 'expiring within ' . $days . ' days</div>';
        } else {
            echo 'expired. Please contact <a target="blank" href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+renew+Magento+SAML+' . $planName . '+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+renew+the+Magento+SAML+' . $planName . '+Plan.+">magentosupport@xecurify.com </a> to renew the license</div>';
        }
    }
}

if ($this->isTrialExpired()) {
    ?>
    <div class="license_note">
        <span
            class="license_note_txt">Your Demo account has been expired. Please contact magentosupport@xecurify.com</span>
    </div>
    <br>
<?php }

echo '	<div style=" padding: 0 1%;">
            <div class="topnav" id="myTopnav">
                <a class="nav-tab ' . ($activeTab == 'account' ? 'active' : '') . '" href="' . $account . '">Account</a>
                <a class="nav-tab ' . ($activeTab == 'multisitesettings' ? 'active' : '') . '" href="' . $multisitesettings . '">Multisite Settings</a>
                <a class="nav-tab ' . ($activeTab == 'idpsettings' ? 'active' : '') . '" href="' . $idpsettings . '">Identity Providers</a>
                <a class="nav-tab ' . ($activeTab == 'spsettings' || $activeTab == 'idps' ? 'active' : '') . '" href="' . $spsettings . '">Service Providers</a>
                <a class="nav-tab ' . ($activeTab == 'signinsettings' ? 'active' : '') . '" href="' . $signinsettings . '">Sign In Settings</a>
                <a class="nav-tab ' . ($activeTab == 'attrsettings' ? 'active' : '') . '" href="' . $attrsettings . '">Attribute Mapping</a>
                <a class="nav-tab ' . ($activeTab == 'rolesettings' ? 'active' : '') . '" href="' . $rolesettings . '">Role Mapping</a>
                <a class="nav-tab ' . ($activeTab == 'upgrade' ? 'active' : '') . '" href="' . $pricing . '">Upgrade</a>
            </div>
        </div>';
