<?php
// initialize all variables
$spsettings = $this->getExtensionPageUrl('spsettings');
$idpsettings = $this->getExtensionPageUrl('idpsettings');
$signinsettings = $this->getExtensionPageUrl('signinsettings');
$attrsettings = $this->getExtensionPageUrl('attrsettings');
$support = $this->getExtensionPageUrl('support');
$formKey = $this->getBlockHtml('formkey');
$is_trial_plan = $this->check_license_plan(4) ? 1 : 0;

echo '
        <div id="userprofile">
            <div style="display: flow-root;">
                <div style="float:left;"><h3>Your Profile</h3></div>

                <form name="f" method="post" action="">
                    ' . $formKey . '
                    <input type="hidden" name="option" value="removeAccount" />
                    <input class="btn-round profilePagebuttons" type="submit" name="submit" id="remove_plugin" value="Remove Account"/>
                </form>

            <!-- Form for Extend Trial action -->
            <form name="extendtrial" method="post" action="">';

if ($is_trial_plan) {
    ?>
    <!-- Form to Extend Trial -->
    <form name="extendtrial" method="post" action="">
        <?php print_r($formKey); ?>
        <input type="hidden" name="option" value="extendTrial"/>
        <input class="btn-round profilePagebuttons" type="submit" style="margin-right:10px;" name="submit"
               id="extend_trial" value="Extend Trial"/>
    </form>

    <?php
}
echo '
</div>
            <hr>
            <p>Thanks for upgrading to premium module.</p>
            <table class="data center">
                <tr>
                    <td><b>miniOrange Account Email</b></td>
                    <td>' . $this->getCustomerEmail() . '</td>
                </tr>
                <tr>
                    <td><b>Customer ID</b></td>
                    <td>' . $this->getCustomerKey() . '</td>
                </tr>
                <tr>
                    <td><b>API Key</b></td>
                    <td>' . $this->getApiKey() . '</td>
                </tr>
                <tr>
                    <td><b>Token Key</b></td>
                    <td>' . $this->getToken() . '</td>
                </tr>
            </table>
        </div>
        <br/>
         <div class="mo_note">
            <div class="btn-link">How do I configure the module?</a></div>
            <div hidden class="collapse">
                <b>The module has step by step instructions on each page to help you. Follow these steps:</b><br/>
                <ol>
                    <li>Go to the Identity Provider Section of the module or <a href="' . $idpsettings . '">click here</a>. On this page follow
                        Step 1 and 2 to configure your IDP.</li>
                    <li>After your IDP is configured go to the Service Provider Section of the module or <a href="' . $spsettings . '">click here</a>.
                        Here enter the values you gathered from your IDP in Step 3 previously.</li>
                    <li>Click on the Test Configuration button on the same page to test your settings.</li>
                    <li>After successful setup, go to the Sign In Settings section of the module or <a href="' . $signinsettings . '">click here</a>.
                        Here decide how you wish for your users to do SSO.</li>
                    <li>Logout and do a final Test.</li>
                </ol>
            </div>
        </div>
        <div class="mo_note">
            <div class="btn-link">I am new to SAML and I don\'t know how to configure the plugin!</a></div>
            <div hidden class="collapse">
                Go to the support section. Drop us a query from the support page or an email at
                magentosupport@xecurify.com and we will get in touch to help you setup the module and site for SSO.
            </div>
        </div>';
