<?php
//Attribute mapping
// initialze all values required to be shown on the page
$roles = $this->getAllRoles();
$groups = $this->getAllGroups();


$isEnabled = $this->isEnabled();
$formKey = $this->getBlockHtml('formkey');
$premiumlink = $this->getExtensionPageUrl('upgrade');
$plantype = !$this->check_license_plan(2) ? 'disabled' : '';

$collection = $this->getAllIdpConfiguration();
$default_provider = $this->getProvider();
$count = 0;
$idpDetails = null;
foreach ($collection as $item) {
    $count++;
    if ($item->getData()["idp_name"] === $default_provider) {
        $idpDetails = $item->getData();
    }
}
if (empty($idpDetails)) {
    foreach ($collection as $item) {
        $idpDetails = $item->getData();
        break;
    }
    if (isset($idpDetails['idp_name'])) {
        $default_provider = $idpDetails['idp_name'];
    }
}
$disabled = !$isEnabled || $count == 0 ? "disabled" : "";
if ($this->isTrialExpired()) {
    $disabled = "disabled";
}
$mo_saml_dont_create_user_if_role_not_mapped = !empty($idpDetails['do_not_autocreate_if_roles_not_mapped']) ? $idpDetails['do_not_autocreate_if_roles_not_mapped'] : "";

$saml_am_update_roles = !empty($idpDetails['update_backend_roles_on_sso']) ? $idpDetails['update_backend_roles_on_sso'] : "";
$saml_am_update_frontend_roles = !empty($idpDetails['update_frontend_groups_on_sso']) ? $idpDetails['update_frontend_groups_on_sso'] : "";

$admin_roles_configured = !empty($idpDetails['roles_mapped']) ? json_decode($idpDetails['roles_mapped']) : "";
$admin_roles_configured = json_decode(json_encode($admin_roles_configured), true);
$customer_roles_configured = !empty($idpDetails['groups_mapped']) ? json_decode($idpDetails['groups_mapped']) : "";
$customer_roles_configured = json_decode(json_encode($customer_roles_configured), true);
$default_role = !empty($idpDetails['default_role']) ? $idpDetails['default_role'] : "";
$default_group = !empty($idpDetails['default_group']) ? $idpDetails['default_group'] : "";

echo '

<div class="row">
<div class="col-sm-8">
    <div class="page" id="attrmapping">
        <div class="mosaml_table_layout">
        ';
if ($this->check_license_plan(3)) {
    echo '
        <form name="select_provider" method="post" action="">
        ' . $formKey . '
        <input type="hidden" name="option" value="saveProvider">
            <tr>
                <td><strong>Identity Provider:</strong></td>
                <td>
                 <select onchange="this.form.submit()" id="mo_identity_provider" ' . $disabled . '  name="mo_identity_provider"
                 style="width:auto;" >';

    foreach ($collection as $item) {
        $selected = $default_provider == $item->getData()["idp_name"] ? 'selected' : '';

        print_r('<option id="mo2f_roles" ' . $selected . '
                            name="' . $item->getData()["idp_name"] . '" value="' . $item->getData()["idp_name"] . '">' .
            $item->getData()["idp_name"] . '</option>');
    }

    echo '
                            </select>
                            <i>Select Identity Provider to configure Group/Role Mapping.</i>
                    </td>
            </tr>
            </form>
            ';
}
echo '
            <br>
            <form name="f" method="post" action="">
                ' . $formKey . '
                <input type="hidden" name="option" value="saveAttrSettings" />
                <input type="hidden" name="mo_identity_provider" value="' . $default_provider . '">
                <h3>Role Mapping (Optional)';
echo (!$this->check_license_plan(2)) ? '<small style="font-weight: bold; font-size: 1.4rem;"><a style="color:red; " href="' . $premiumlink . '"
                class="premium premium-btn-link">[PREMIUM]</a></small>' : '';
echo '</h3><hr/>
                <table>
                        <tr>
                        <td colspan="2">
                            <div class="mo_note">
                                <span class="btn-link" href="">What is Role Mapping?</span>
                                <div hidden class="collapse">
                                    <ol>
                                        <li>Magento uses a concept of Roles, designed to give the site owner the ability to control
                                                what users can and cannot do within the site.</li>
                                        <li>Role mapping helps you to assign specific roles to users of a certain group in your IdP.</li>
                                        <li>While auto registering, the users are assigned roles based on the group they are mapped to.</li>
                                    </ol>
                                </div>
                            </div>
                        </td>
                        </tr>
                    <tr><td colspan="2"><b>NOTE: </b>Role will be assigned only to non-admin users (user that do NOT have Administrator
                        privileges). You will have to manually change the role of Administrator users.</td></tr>
                    <tr><td colspan="2"><input type="checkbox" id="dont_create_user_if_role_not_mapped"
                        name="mo_saml_dont_create_user_if_role_not_mapped" value="checked"
                        ' . $mo_saml_dont_create_user_if_role_not_mapped . '
                        ' . $disabled . ' ' . $plantype . ' />&nbsp;&nbsp;Do not auto create users if roles are not
                        mapped here.</td></tr>
                    <tr><td colspan="2"><input type="checkbox" id="update_roles"
                        name="saml_am_update_roles" value="checked"
                        ' . $saml_am_update_roles . ' ' . $disabled . '  ' . $plantype . '>
                        &nbsp;&nbsp;Update Backend Roles on SSO.</td></tr>
                    <tr><td colspan="2"><input type="checkbox" id="update_frontend_roles"
                        name="saml_am_update_frontend_roles" value="checked"
                        ' . $saml_am_update_frontend_roles . ' ' . $disabled . ' ' . $plantype . ' >
                        &nbsp;&nbsp;Update Frontend Roles on SSO.</td></tr>
                    <tr>

                    <tr>
                        <td><strong>Default Role (For Backend Users):</strong></td>
                        <td>
                                <select id="saml_am_default_role" name="saml_am_default_role"
                                     ' . $disabled . ' ' . $plantype . ' style="width:150px;" >';

foreach ($roles as $role) {
    $selected = $default_role == $role['label'] ? 'selected' : '';
    echo '<option id="mo2f_roles" ' . $selected . '
                                        name="' . $role['label'] . '" value="' . $role['label'] . '"/>' .
        $role['label'] . '</option>';
}
echo '                           </select>   <i>Select the default role to assign to new Users.</i>
                        </td>
                    </tr>';


foreach ($roles as $role) {
    $role_value = $role['value'];
    $role_name = $role['label'];
    if (empty($admin_roles_configured)) {
        $admin_roles = [];
        $value = !empty($admin_roles[$role_value]) ? $admin_roles[$role_value] : "";
    } else {
        $admin_roles = (array)$admin_roles_configured;
        $value = !empty($admin_roles[$role_value]) ? $admin_roles[$role_value] : "";
    }
    echo '<tr><td><b>' . $role_name . '</b></td><td><input type="text" name="saml_am_admin_attr_values_' .
        $role_value . '" value="' . $value . '" placeholder="Semi-colon(;) separated Roles for ' .
        $role_name . '" style="width: 400px;"' . $disabled . ' ' . $plantype . ' /></td></tr>';
}

echo '
                    <td><tr></tr>
                    <tr  style="border-bottom: 1px solid #c1bdbd;">
                    <tr>
                    <td><tr></tr>
                        <td><strong>Default Group (For Frontend Users):</strong></td>
                        <td>
                                <select id="saml_am_default_group" name="saml_am_default_group"
                                     ' . $disabled . ' ' . $plantype . ' style="width:150px;" >';

foreach ($groups as $group) {
    $selected = $default_group == $group['label'] ? 'selected' : '';
    echo '<option id="mo2f_groups" ' . $selected . ' name="' .
        $group['label'] . '" value="' . $group['label'] . '"/>' .
        $group['label'] . '</option>';
}

echo '                           </select> <i>Select the default role to assign to new Users.</i>
                        </td>
                    </tr>';

foreach ($groups as $group) {
    $role_value = $group['value'];
    $role_name = $group['label'];
    $value = !empty($customer_roles_configured[$role_value]) ? $customer_roles_configured[$role_value] : "";

    echo '<tr> <td><b>' . $role_name . '</b></td>
                                    <td><input type="text" name="saml_am_group_attr_values_' .
        $role_value . '" value="' . $value . '" placeholder="Semi-colon(;) separated Group value for ' .
        $role_name . '" style="width: 400px;"' . $disabled . ' ' . $plantype . ' />
                                    </td>
                            </tr>';
}

echo '               <tr>
                        <td>&nbsp;</td>
                        <td><br /><input type="submit" style="width:100px;" name="submit" value="Save"
                        class="btn-round" ' . $disabled . ' ' . $plantype . ' /> &nbsp;
                        <br /><br />
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
';
