<!--
	This template file is for the Sign In settings.
	File acts as a view file for our Sign In settings.
-->
<?php
// initialize all values
$byPassRedirect = $this->isByBackDoorEnabled() ? 'checked' : '';
$isSPConfigured = $this->isSPConfigured() && $this->isEnabled();
$premiumlink = $this->getExtensionPageUrl('upgrade');

$formKey = $this->getBlockHtml('formkey');

$collection = $this->getAllIdpConfiguration();
$default_provider = $this->getProvider();

$idpDetails = null;
$count = 0;
foreach ($collection as $item) {
    $count++;
    if ($item->getData()["idp_name"] === $default_provider) {
        $idpDetails = $item->getData();
    }
}
if (empty($idpDetails)) {
    foreach ($collection as $item) {
        $idpDetails = $item->getData();
        break;
    }
    if (isset($idpDetails['idp_name'])) {
        $default_provider = $idpDetails['idp_name'];
    }
}
$disabled = $isSPConfigured && $count > 0 ? "" : 'disabled title="Disabled. Configure your Service Provider" ';
if ($this->isTrialExpired()) {
    $disabled = "disabled";
}
$adminLink = !empty($idpDetails) ? ($idpDetails['show_admin_link'] ? 'checked' : '') : '';
$autoCreateAdmin = !empty($idpDetails) ? ($idpDetails['auto_create_admin_users'] ? 'checked' : '') : '';
$customerLink = !empty($idpDetails) ? ($idpDetails['show_customer_link'] ? 'checked' : '') : '';
$autoCreateCustomer = !empty($idpDetails) ? ($idpDetails['auto_create_customers'] ? 'checked' : '') : '';
$login_redirect = !empty($idpDetails) ? ($idpDetails['auto_redirect_to_idp'] ? 'checked' : '') : '';

$idpDetails['idp_name'] = !empty($idpDetails['idp_name']) ? $idpDetails['idp_name'] : 'IDP_Name';
$logoutRedirectUrl = !empty($idpDetails['saml_logout_redirect_url']) ? $idpDetails['saml_logout_redirect_url'] : '';
$getBaseUrl = $this->getBaseUrl();
$idpname = $idpDetails['idp_name'];
$all_page_login_redirect = $this->isAllPageAutoRedirectEnabled($idpname) ? 'checked' : '';
$login_redirect = $this->isAutoRedirectEnabled($idpname) ? 'checked' : '';
$enabledebuglog = $this->isDebugLogEnable() ? 'checked' : '';
$mo_saml_headless_sso = !empty($idpDetails['mo_saml_headless_sso']) && $idpDetails['mo_saml_headless_sso'] == 1 ? 'checked' : '';
$frontendPostUrl = !empty($idpDetails['mo_saml_frontend_post_url']) ? $idpDetails['mo_saml_frontend_post_url'] : '';
$autoredirect_admin_loginPage = $this->isAdminAutoRedirectEnabled($default_provider)? 'checked':'';
$adminBackDoorUrl = $this->getAdminBackdoorUrl();
?>

<div class="row">
    <div class="col-sm-8">
        <div class="page" id="samlsettings">
            <div class="mosp_table_layout">
                <?php if ($this->check_license_plan(3)) { ?>
                    <form name="select_provider" method="post" action="">
                        <?php print_r($formKey); ?>
                        <input type="hidden" name="option" value="saveProvider">
                        <tr>
                            <td><strong>Identity Provider:</strong></td>
                            <td>
                                <select onchange=this.form.submit()
                                        id="mo_identity_provider" <?php print_r($disabled); ?>
                                        name="mo_identity_provider" style="width:auto;">
                                    <?php
                                    foreach ($collection as $item) {
                                        $selected = $default_provider == $item->getData()["idp_name"] ? 'selected' : ''; ?>

                                        <option id="mo2f_roles" <?php print_r($selected) ?>
                                                name= <?php print_r($item->getData()["idp_name"]) ?>
                                                value=<?php print_r($item->getData()["idp_name"]) ?>>
                                            <?php print_r($item->getData()["idp_name"]) ?></option>
                                        <?php
                                    } ?></select>
                                <i>Select Identity Provider to configure Sign In Settings.</i>

                            </td>
                        </tr>
                    </form>
                <?php } ?>

                <br>
                <h3>SIGN IN OPTIONS</h3>
                <hr>
                <form name="f" method="post" action="">
                    <?php print_r($formKey); ?>
                    <input type="hidden" name="option" value="saveSingInSettings"/>
                    <input type="hidden" name="mo_identity_provider" value= <?php print_r($default_provider) ?>>
                    <table style="width:100%;">
                        <tr>
                            <td><span
                                    style="width: 20%;"><strong>Post-Logout URL:</strong></span><?php echo (!$this->check_license_plan(2)) ? '<small style="color:red"><a style="color:red; " href="' . $premiumlink . '"
                class="premium premium-btn-link">[PREMIUM]</a></small>' : ''; ?><br>
                            </td>
                            <td><input <?php echo (!$this->check_license_plan(2)) ? 'disabled' : ''; ?>
                                    style="width:200%" type="text" <?php print_r($disabled); ?>
                                    id="mo_saml_logout_redirect_url" name="mo_saml_logout_redirect_url"
                                    value="<?php print_r($logoutRedirectUrl); ?>"/></td>
                        </tr>
                    </table>
                    <table>

                        <tr>
                            <br>

                            <br/>
                            <h4><b>Show Link on Default Login Page :</b></h4>
                            <div style="margin-left:17px;margin-top:2%;">
                                <input <?php echo (!$this->check_license_plan(2)) ? 'disabled' : ''; ?> type="checkbox"
                                                                                                        name="mo_saml_show_admin_link"
                                                                                                        id="mo_saml_show_admin_link"
                                    <?php print_r($disabled); ?> <?php print_r($adminLink); ?> value="true"> Enable
                                admin SSO and Show the Login Link on the default admin login
                                page.<?php echo (!$this->check_license_plan(2)) ? '<small style="color:red"><a style="color:red; " href="' . $premiumlink . '"
                class="premium premium-btn-link">[PREMIUM]</a></small>' : ''; ?>
                                <br><br>
                                <input type="checkbox" name="mo_saml_show_customer_link" id="mo_saml_show_customer_link"
                                    <?php print_r($customerLink); ?> <?php print_r($disabled); ?> value="true"> Show the
                                Login Link on the default customer login page.
                            </div>
                        </tr>


                        <tr>
                            <br>

                            <br/>
                            <h4><b>User Auto Create Settings :</b></h4>
                            <div style="margin-left:17px;margin-top:2%;">
                                <input <?php echo (!$this->check_license_plan(2)) ? 'disabled' : ''; ?> type="checkbox"
                                                                                                        name="mo_saml_auto_create_admin"
                                                                                                        id="mo_saml_auto_create_admin"
                                    <?php print_r($autoCreateAdmin); ?> <?php print_r($disabled); ?> value="true"> Auto
                                Create Admin users while SSO, if they do not
                                exist.<?php echo (!$this->check_license_plan(2)) ? '<small style="color:red"><a style="color:red; " href="' . $premiumlink . '"
                class="premium premium-btn-link">[PREMIUM]</a></small>' : ''; ?>
                                <br><br>
                                <input type="checkbox" name="mo_saml_auto_create_customer"
                                       id="mo_saml_auto_create_customer"
                                    <?php print_r($autoCreateCustomer); ?> <?php print_r($disabled); ?> value="true">
                                Auto Create Customers while SSO, if they do not exist.
                            </div>
                            <br> <br/>
                        </tr>


                        <tr>

                            <h4><b> User Auto Redirect Settings:</b></h4>
                            <div style="margin-left:17px;margin-top:2%;">
                                <input <?php echo (!$this->check_license_plan(2)) ? 'disabled' : ''; ?> type="checkbox"
                                                                                                        name="mo_saml_enable_login_redirect"
                                                                                                        value="true"
                                    <?php print_r($disabled); ?> <?php print_r($login_redirect); ?> />
                                Check this option to <b>auto redirect users to IdP</b> from customer login page (if not logged
                                in).<?php echo (!$this->check_license_plan(2)) ? '<small style="color:red"><a style="color:red; " href="' . $premiumlink . '"
                class="premium premium-btn-link">[PREMIUM]</a></small>' : ''; ?></b>

                                <span class="tooltip">
                                    <div class="admin__field-tooltip tooltip">
                                        <a title="What is this?" class="admin__field-tooltip-action action-help"><span>What is this?</span></a>
                                    </div>
                                    <span class="tooltiptext"><span class="header"><b><i>WHAT IS THIS?</i></b></span><hr>
                                    <span class="body"
                                          style="width:20px">Users from customer login page URLs will get redirected </br> to your
                                    configured IdP for authentication.</span></span>
                                </span>
                                <br><br>

                                <input <?php echo (!$this->check_license_plan(2)) ? 'disabled' : ''; ?> type="checkbox"
                                                                                                        name="mo_saml_enable_admin_login_redirect"
                                                                                                        value="true"
                                    <?php print_r($disabled); ?><?php print_r($autoredirect_admin_loginPage); ?>/>
                                Check this option to <b>auto redirect users to IdP</b> from Admin login page (if not logged
                                in).<?php echo (!$this->check_license_plan(2)) ? '<small style="color:red"><a style="color:red; " href="' . $premiumlink . '"
                class="premium premium-btn-link">[PREMIUM]</a></small>' : ''; ?></b>

                                <span class="tooltip">
                                    <div class="admin__field-tooltip tooltip">
                                        <a title="What is this?" class="admin__field-tooltip-action action-help"><span>What is this?</span></a>
                                    </div>
                                    <span class="tooltiptext"><span class="header"><b><i>WHAT IS THIS?</i></b></span><hr>
                                    <span class="body"
                                          style="width:20px">Users from Admin login page URL will get redirected </br> to your
                                    configured IdP for authentication.</span></span>
                                </span>
                                <br><br>

                                <input <?php echo (!$this->check_license_plan(2)) ? 'disabled' : ''; ?>
                                    type="checkbox" <?php print_r($disabled); ?>
                                    name="mo_saml_enable_all_page_login_redirect" value="true"
                                    <?php print_r($all_page_login_redirect); ?> />
                                Check this option to <b>auto redirect users to IdP</b> from any page (if not logged
                                in).<?php echo (!$this->check_license_plan(2)) ? '<small style="color:red"><a style="color:red; " href="' . $premiumlink . '"
                class="premium premium-btn-link">[PREMIUM]</a></small>' : ''; ?>

                                <span class="tooltip">
                             <div class="admin__field-tooltip tooltip">
                                 <a title="What is this?" class="admin__field-tooltip-action action-help"><span>What is this?</span></a>
                             </div>
                             <span class="tooltiptext"><span class="header"><b><i>WHAT IS THIS?</i></b></span><hr>
                             <span class="body">Users from all page URLs will get redirected to </br> your
                             configured IdP for authentication</span></span>
                         </span>

                                <div style="margin-left: 2.5em;color: #F10C0C;font-style: italic;font-size: small">
                                </div>
                            </div>

                        </tr>

                        <br><br>
                        <h4><b>Admin Backdoor URL:</b></h4>
                        <div style="font-style: italic;border: 1px solid #c2c2c2;-webkit-box-shadow: 1px 1px 4px #ebebeb;padding:7px" > <?php print_r($adminBackDoorUrl); ?> </div>

                        <tr>
                            <br>
                            <h4><b>Use a SSO link:</b></h4>
                            <div style="margin-bottom:15px;margin-top:-10px">Use the following link to initiate SSO.
                            </div>
                            <div
                                style="font-style: italic;border: 1px solid #c2c2c2;-webkit-box-shadow: 1px 1px 4px #ebebeb;padding:7px"> <?php echo $getBaseUrl . "mospsaml/actions/sendAuthnRequest?idp_name=$idpname&relayState={Enter your redirect url here}"; ?> </div>


                            <br>
                            <h4><b>Headless SSO:</b></h4>
                            <input type="checkbox" name="mo_saml_headless_sso" id="mo_saml_headless_sso"
                                <?php print_r($mo_saml_headless_sso); ?> <?php print_r($disabled); ?> value="true">
                            Check this option to <b>activate Headless SSO</b>.

                            <table style="width:100%;">
                                <tr>
                                    <td><span style="width: 20%;"><strong>Frontend Post URL:</strong></span><br>
                                    </td>
                                    <td><input <?php echo (!$this->check_license_plan(2)) ? 'disabled' : ''; ?>
                                            style="width:200%" type="text" <?php print_r($disabled); ?>
                                            id="mo_saml_frontend_post_url" name="mo_saml_frontend_post_url"
                                            value="<?php print_r($frontendPostUrl); ?>"/></td>
                            </table>
                            <br>
                            <input type="submit" class="btn-round btn-width" name="link_setup"
                                   title="You can only make changes if you have configured your SP"
                                   onclick="document.getElementById(\'signInSettings\').submit(); "
                                <?php print_r($disabled); ?> value="Save" style="width:150px"/>
                            <br/><br/>

                        </tr>

                    </table>
                </form>
                <br><br><br>

                <h3>DEBUG LOGS</h3>
                <hr>
                <form id="enable_debug_log" method="post" action="">
                    <?php print_r($formKey); ?>
                    <input type="hidden" name="option" value="enable_debug_log">
                    <input type="hidden" name="mo_identity_provider" value= <?php print_r($default_provider) ?>>

                    <br>
                    <input type="checkbox" name="debug_log_on" <?php print_r($enabledebuglog); ?> value="true"
                           $disabled>Enable Debug Log

                    <input type="submit" $disabled class="btn-round" name="enable_debug_log"
                           onclick="document.getElementById(\'enable_debug_log\').submit(); " value="Submit"
                           style="width:110px; margin-left:30px">
                    <br>
                </form>
                <form id="clear_download_logs" method="post" action="">
                    <?php print_r($formKey); ?>
                    <input type="hidden" name="option" value="clear_download_logs">
                    <input type="hidden" name="mo_identity_provider" value= <?php print_r($default_provider) ?>>
                    <p style="margin-top:20px;margin-left:10px">The error logs will cleared automatically on weekly
                        basis. </p>

                    <div style="text-align:left">
                        <br>
                        <input type="submit" $disabled class="btn-round" name="download_logs"
                               onclick="document.getElementById(\'download_logs\').submit(); " value="Download Logs"
                               style="width:150px; margin-left:10px">
                        <input <?php print_r($disabled); ?> type="submit" class="btn-round" name="clear_logs"
                                                            value="Clear Logs" style="width:150px; margin-left:10px">
                    </div>

                </form>
            </div>
        </div>
