<!--
	This template file is for the SAML Service Provider settings.
	File acts as a view file for our Service Provider settings.
-->
<?php
// initialize all values
$isEnabled = $this->isEnabled() ? "" : "disabled";
if ($this->isTrialExpired()) {
    $isEnabled = "disabled";
}
$idps = $this->getExtensionPageUrl('idps');
$testUrl = $this->getTestUrl();
$formKey = $this->getBlockHtml('formkey');

$default_provider = $this->getProvider();
$selected_provider = null;
$params = $this->getRequest()->getParams();
if (!empty($default_provider)) {
    $count = 0;
    $collection = $this->getAllIdpConfiguration();
    $defaultConfigurations = null;
    foreach ($collection as $item) {
        $count++;
        if ($item->getData()["idp_name"] === $default_provider) {
            $defaultConfigurations = $item->getData();
        }
    }
    if (!empty($defaultConfigurations)) {
        $idp_name = !empty($defaultConfigurations['idp_name']) ? $defaultConfigurations['idp_name'] : null;
        $httpLogoutRedirect = !empty($defaultConfigurations['saml_logout_binding']) && $defaultConfigurations['saml_logout_binding'] == 'HttpRedirect' || empty($defaultConfigurations['saml_logout_binding']) ? 'checked="checked"' : '';
        $httpLoginRedirect = !empty($defaultConfigurations['saml_login_binding']) && $defaultConfigurations['saml_login_binding'] == 'HttpRedirect' || $defaultConfigurations['saml_login_binding'] ? 'checked="checked"' : '';
        $httpLogoutPost = !empty($defaultConfigurations['saml_logout_binding']) && $defaultConfigurations['saml_logout_binding'] == 'HttpPost' ? 'checked="checked"' : '';
        $httpLoginPost = !empty($defaultConfigurations['saml_login_binding']) && $defaultConfigurations['saml_login_binding'] == 'HttpPost' ? 'checked="checked"' : '';
        $testUrl = !empty($idp_name) ? $this->getTestUrl($idp_name) : null;
        $isResponseSigned = !empty($defaultConfigurations['response_signed']) && $defaultConfigurations['response_signed'] == 1 ? "checked" : "";
        $isAssertionSigned = !empty($defaultConfigurations['assertion_signed']) && $defaultConfigurations['assertion_signed'] == 1 ? "checked" : "";
    } else
        $default_provider = '';
}
if (!empty($params['edit'])) {
    $selected_provider = $params['idp_name'];

    $collection = $this->getAllIdpConfiguration();
    $idpDetails = null;
    foreach ($collection as $item) {
        if ($item->getData()["idp_name"] === $selected_provider) {
            $idpDetails = $item->getData();
        }
    }
    $idp_name = !empty($idpDetails['idp_name']) ? $idpDetails['idp_name'] : null;
    $httpLogoutRedirect = !empty($idpDetails['saml_logout_binding']) && $idpDetails['saml_logout_binding'] == 'HttpRedirect' || empty($idpDetails['saml_logout_binding']) ? 'checked="checked"' : '';
    $httpLoginRedirect = !empty($idpDetails['saml_login_binding']) && $idpDetails['saml_login_binding'] == 'HttpRedirect' || $idpDetails['saml_login_binding'] ? 'checked="checked"' : '';
    $httpLogoutPost = !empty($idpDetails['saml_logout_binding']) && $idpDetails['saml_logout_binding'] == 'HttpPost' ? 'checked="checked"' : '';
    $httpLoginPost = !empty($idpDetails['saml_login_binding']) && $idpDetails['saml_login_binding'] == 'HttpPost' ? 'checked="checked"' : '';
    $testUrl = !empty($idp_name) ? $this->getTestUrl($idp_name) : '';
    $isResponseSigned = !empty($idpDetails['response_signed']) && $idpDetails['response_signed'] == 1 ? "checked" : "";
    $isAssertionSigned = !empty($idpDetails['assertion_signed']) && $idpDetails['assertion_signed'] == 1 ? "checked" : "";
} elseif (!empty($params['add'])) {
    $selected_provider = null;
    $isResponseSigned = null;
    $isAssertionSigned = null;

    $httpLogoutPost = null;

    $httpLoginPost = null;

    $httpLoginRedirect = null;

    $httpLogoutRedirect = null;
} else {
    $selected_provider = null;
    $isResponseSigned = null;
    $isAssertionSigned = null;

    if (empty($httpLogoutPost))
        $httpLogoutPost = null;

    if (empty($httpLoginPost))
        $httpLoginPost = null;

    if (empty($httpLoginRedirect))
        $httpLoginRedirect = null;

    if (empty($httpLogoutRedirect))
        $httpLogoutRedirect = null;
}

echo '
	<script>
		var testURL = "' . $testUrl . '";
	</script>
	<div class="row">
<div class="col-sm-8">
	<div class="page" id="serviceprovider">
	<div class="upload_metadata_div"">

		<form method="post" id="upload_metadata_form" class="upload_metadata_form" enctype="multipart/form-data">
		' . $formKey . '
			<input type="hidden" name="option" value="upload_metadata_file">
			';
if ($selected_provider != null) {
    echo '
			<input type="hidden" name="selected_provider" value=' . $idpDetails['idp_name'] . '>';
}
echo '
			<div style="display:inline">
				<label for="idp_name"><b>Identity Provider Name: </b></label>
				<input type="text" id="upload_identity_name" name="saml_identity_name" placeholder="Identity Provider name like ADFS, Salesforce" ';
if ($selected_provider != null && !empty($idpDetails['idp_name'])) {
    echo "disabled value=" . $idpDetails['idp_name'];
} else if (!empty($params['add'])) {
    echo " value=''";
} else if (!empty($default_provider) && !empty($defaultConfigurations['idp_name'])) {
    echo " value=" . $defaultConfigurations['idp_name'];
}
echo " required " . $isEnabled;
echo 'pattern="^\w*$" title="Only alphabets, numbers and underscore is allowed" style="width: 350px;">
			</div>
			<div style="display:inline">
				<h4><strong>Upload IDP XML Metadata</strong></h4>
			</div>
				<hr style="border: 1px solid rgb(131, 128, 128)">
			<br>
			<div>
					<label for="metadata"><b>Upload File: </b></label>
					<input class="form-control" id="metadata_file" type="file" name="metadata_file" data-validate="{required:true}">
			</div>
			<h4 style="text-align:center;">OR</h4>
			<div>
				<label for="upload_url"><b>Upload URL: </b></label>
				<input class="form-control" type="url" name="upload_url">
			</div>
			<br>
			<br>
			<div style="text-align:center;">
			<input type="submit" name="upload_file" onClick="uploadFile()" id="upload_file" class="btn-round" name="submit" style="width:19%; margin-left: -2%" value="Save" ' . $isEnabled . '>
			<a class="btn btn-primary cancel btn-round" style="background-color:#b82727; color:white; padding:2%" type="button"  name="cancel" id="cancel" onClick="cancel()">Cancel</a>
			</form>
			</div>
		</div>
		<div class="mosp_table_layout">


			<form name="f" id="spsettings" method="post" action="">
				' . $formKey . '
				<input type="hidden" name="option" value="saveIDPSettings">
				';
if ($selected_provider != null) {
    echo '
			<input type="hidden" name="selected_provider" value=' . $idpDetails['idp_name'] . '>';
}
echo '
				<h3>CONFIGURE SERVICE PROVIDER</h3>
				<hr>
				Enter the information gathered from your Identity Provider
				<input class="btn-round" type="button" name="upload_idp_metadata" onclick="upload_metadata();" style="float:right; margin-right:20%; margin-top:1%; width:20%;" ' . $isEnabled . '   value="Upload IDP Metadata"/>

				<table style="width:200%;">
					<tr>
						<td style="width:35%;"><strong>Identity Provider Name<span style="color:red;">*</span>:</strong></td>
						<td style="width:170%;"><input type="text" name="saml_identity_name" placeholder="Identity Provider name like ADFS, SimpleSAML, Salesforce"
								';
if ($selected_provider != null && !empty($idpDetails['idp_name'])) {
    echo "disabled value=" . $idpDetails['idp_name'];
} else if (!empty($params['add'])) {
    echo " value=''";
} else if (!empty($default_provider) && !empty($defaultConfigurations['idp_name'])) {
    echo " value=" . $defaultConfigurations['idp_name'];
}
echo " required " . $isEnabled;
echo ' pattern="^\w*$" title="Only alphabets, numbers and underscore is allowed"></td>
					</tr>
					<tr>
						<td><strong>IdP Entity ID or Issuer <span style="color:red;width:30%;">*</span>:</strong></td>
						<td><input type="text" name="saml_issuer" placeholder="Identity Provider Entity ID or Issuer"
						';
if ($selected_provider != null && !empty($idpDetails['idp_entity_id'])) {
    echo "value=" . $idpDetails['idp_entity_id'];
} else if (!empty($params['add'])) {
    echo " value=''";
} else if (!empty($default_provider) && !empty($defaultConfigurations['idp_entity_id'])) {
    echo " value=" . $defaultConfigurations['idp_entity_id'];
}
echo " required " . $isEnabled;
echo ' required ' . $isEnabled . '></td>
					</tr>
					<tr>
						<td><strong>SAML Login URL<span style="color:red;">*</span>:</strong></td>
						<td><input type="url" name="saml_login_url" placeholder="Single Sign On Service URL of your IdP"
						';
if ($selected_provider != null && !empty($idpDetails['saml_login_url'])) {
    echo "value=" . $idpDetails['saml_login_url'];
} else if (!empty($params['add'])) {
    echo " value=''";
} else if (!empty($default_provider) && !empty($defaultConfigurations['saml_login_url'])) {
    echo " value=" . $defaultConfigurations['saml_login_url'];
}
echo " required " . $isEnabled;
echo ' required ' . $isEnabled . '></td>
					</tr>
					<tr>
						<td><strong>SAML Login Binding :</strong></td>

						<td><input style="width:5%;" type="radio" name="saml_login_binding_type" id="sli-http-redirect" value="HttpRedirect"
						' . $httpLoginRedirect . ' ' . $isEnabled . '>HTTP-Redirect Binding</input>
						<input style="width:5%; margin-left: 5%" type="radio" name="saml_login_binding_type" id="sli-http-post"
						value="HttpPost" ' . $httpLoginPost . ' ' . $isEnabled . '>HTTP-POST Binding</input>
						<br></td>
					</tr>
					<tr>
						<td><strong>SAML Logout URL :</strong></td>
						<td><input type="url" name="saml_logout_url" placeholder="Single Logout Service URL of your IdP"
						';
if ($selected_provider != null && !empty($idpDetails['saml_logout_url'])) {
    echo "value=" . $idpDetails['saml_logout_url'];
} else if (!empty($params['add'])) {
    echo " value=''";
} else if (!empty($default_provider) && !empty($defaultConfigurations['saml_logout_url'])) {
    echo "value=" . $defaultConfigurations['saml_logout_url'];
}
echo "" . $isEnabled;
echo ' ' . $isEnabled . '></td>
					</tr>
					<tr>
						<td><strong>SAML Logout Binding : </strong></td>
						<td><input style="width:5%;" type="radio" name="saml_logout_binding_type" id="slo-http-redirect" value="HttpRedirect"
							' . $httpLogoutRedirect . ' ' . $isEnabled . '>HTTP-Redirect Binding</input>
						<input style="width:5%;margin-left: 5%" type="radio" name="saml_logout_binding_type" id="slo-http-post"
							value="HttpPost" ' . $httpLogoutPost . ' ' . $isEnabled . '>HTTP-POST Binding</input>
						<br></td>

					</tr>

					<tr>
						<td><strong>X.509 Certificate <span style="color:red;">*</span>:</strong></td>
						<td>
							<textarea required style="height:30%" rows="4" cols="5" name="saml_x509_certificate"
								placeholder="Copy and Paste the content from the downloaded certificate or copy the content enclosed in
									\'X509Certificate\' tag (has parent tag \'KeyDescriptor use=signing\') in IdP-Metadata XML file"
								 ' . $isEnabled . ' >';
if ($selected_provider != null && !empty($idpDetails['x509_certificate'])) {
    echo $idpDetails['x509_certificate'];
} else if (!empty($params['add'])) {
    echo '';
} else if (!empty($default_provider) && !empty($defaultConfigurations['x509_certificate'])) {
    echo $defaultConfigurations['x509_certificate'];
}
echo $isEnabled;
echo '
							</textarea>
						</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>
							<b>NOTE:</b> Format of the certificate:<br/><b>-----BEGIN CERTIFICATE-----<br/>XXXXXXXXXXXXXXXXXXXXXXXXXXX
								<br/>-----END CERTIFICATE-----</b></i><br/>
						</td>
					</tr>

					<tr>
						<td>&nbsp;</td>
						<td>
							<br><input type="submit" class="btn-round" name="submit" style="width:19%; margin-left: -2%" value="Save"
							' . $isEnabled . '> &nbsp;
							<input class="btn-round" type="button" name="test" title="You can only test your Configuration after saving your Service Provider Settings."
								onclick="showTestWindow();"' . $isEnabled . ' value="Test configuration" style="width:45%;">
						</td>
					</tr>
				</table>
			</form>
			';
if ($this->check_license_plan(3)) {
    echo '
			<form method="post" id="add-identity-provider-form" action="' . $idps . '">
        ' . $formKey . '
        <input id= ""type="hidden" name="option" value="goBack">

        <input type="submit" ' . $isEnabled . ' value="Go Back" style="width:11%; margin-right:37%; float:right; margin-top: -5%" class="btn btn-small btn-danger btn-round"/></form>
		';
}
echo '
		</div>
	</div>';
