<?php

$formKey = $this->getBlockHtml('formkey');
$supportUrl = $this->getUrl('mospsaml/support/index');
$isEnabled = $this->isEnabled();
$disabled = !$isEnabled ? "disabled" : "";

echo '

<div class="panel-heading">
	<div class="pull-right">
		<div class="page" id="minisupport" style="margin-top:11px;">
            <div class="mosp_table_layout">


                <h3>SUPPORT</h3>
                <hr>
                <form name="f" id="support" method="post" action= "' . $supportUrl . '">
                    ' . $formKey . '
                    <div><b>Need any help? Just send us a query so we can help you.</b><br /><br/></div>
                    <input type="hidden" name="option" value="supportQuery" />
                    <div>
                        <table>
                            <tr><td>
                                <input type="email"  class="mosp_table_textbox" id="query_email" name="email" value="" placeholder="Enter your email" required="true" />
                                </td>
                            </tr>
                            <tr><td>
                                <input type="text"  class="mosp_table_textbox" name="phone" id="query_phone" title="Phone with country code eg. +1xxxxxxxxxx" placeholder="Phone with country code eg. +1xxxxxxxxxx" value="" pattern="[\+]?[0-9]{1,4}\s?[0-9]{10}"/>
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <textarea id="query"  class="mosp_table_textbox" name="query" style="resize:vertical;height:120px;" onkeyup="mosp_valid(this)" onblur="mosp_valid(this)" onkeypress="mosp_valid(this)" placeholder="Write your query here"></textarea>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <input class="btn-round" style="width:50%;margin-left:25%;" type="submit" name="send_query"  id="send_query" value="Submit Query" style="margin-left:10%;"  />
                 </form>
                <br />
            </div>
            <br>
        </div>

    </div>
    </div>
    </div>';
