<!--Pricing Tab-->
<?php

$idpsettings = $this->getExtensionPageUrl('idpsettings');
$hostname = $this->getMiniOrangeUrl();
$email = $this->getCustomerEmail();
$version = $this->getCurrentVersion();
$plantype = !$this->check_license_plan(2) ? 'disabled' : '';


echo '
     <div class="page" id="pricing">

      <section class="pricing py-5">

      <div class="container">

      <div class="row">

        <!-- Free Tier -->
        <div class="columns">

              <ul class="price">

                <li class="header">Free/Trial</li>

                <li class="grey">$0</li>

                <li>&#10004Auto Create Users (Upto 10 Users)</li>

                <li>&#10004Option to Add SSO login button</li>

                <li>&#10004Options to select SAML Request binding type</li>

                <li>&#10004Unlimited authentication via IDP</li>

                <li><s>IDP and SP Initiated SSO</s></li>

                <li><s>Option to select SAML Request</s></li>

                <li><s>SAML Single Logout</s></li>

                <li><s>Auto-Redirect to IDP from login page</s></li>

                <li><s>End to End Provider Configuration</s></li>

                <li><s>Default Attribute Mapping</s></li>

                <li><s>Custom Attribute Mapping</s></li>

                <li><s>Role Mapping</s></li>

                <li><s>Support for multi-store</s></li>

                <li><s>Support for multisites</s>

                </li>
                 <li><a href="#" class="button btn-round">Upgrade Now</a></li>

               </ul>

            </div>
            <!-- Plus Tier -->
            <div class="columns">

            <ul class="price">

               <li class="header" ';
echo ($this->check_license_plan(1) && !$this->check_license_plan(2) && !$this->check_license_plan(2)) ? 'style="background-color: #ea680b" ' : '';
echo '>Standard';
echo ($this->check_license_plan(1) && !$this->check_license_plan(2) && !$this->check_license_plan(2)) ? '<small>' . $version . '</small>' : '';
echo '</li>

               <li class="grey">$299*</li>

               <li>&#10004Auto Create Users (Unlimited)</li>

               <li>&#10004Option to Add SSO login button</li>

               <li>&#10004Options to select SAML Request binding type</li>

               <li>&#10004Unlimited authentication via IDP</li>

               <li>&#10004IDP and SP Initiated SSO</li>

               <li>&#10004Option to select SAML Request</li>

               <li><s>SAML Single Logout</s></li>

               <li><s>Auto-Redirect to IDP from login page</s></li>

               <li><s>End to End Provider Configuration</s></li>

               <li><s>Default Attribute Mapping</s></li>

               <li><s>Custom Attribute Mapping</s></li>

               <li><s>Role Mapping</s></li>

               <li><s>Support for multi-store</s></li>

               <li><s>Support for multisites</s></li>

               <li><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+SAML+Standard+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+SAML+Standard+Plan.+" class="button btn-round">Upgrade Now</a></li>

          </ul>

        </div>


        <!-- Pro Tier -->
        <div class="columns">

        <ul class="price">

                <li class="header" ';
echo (!$this->check_license_plan(3) && $this->check_license_plan(2)) ? ' style="background-color: #ea680b"  ' : '';
echo '>Premium ';
echo (!$this->check_license_plan(3) && $this->check_license_plan(2)) ? '<small>' . $version . '</small>' : '';
echo ' </li>

                <li class="grey">$399*</li>

                <li>&#10004Auto Create Users (Unlimited)</li>

                <li>&#10004Option to Add SSO login button</li>

                <li>&#10004Options to select SAML Request binding type</li>

                <li>&#10004Unlimited authentication via IDP</li>

                <li>&#10004IDP and SP Initiated SSO</li>

                <li>&#10004Option to select SAML Request</li>

                <li>&#10004SAML Single Logout</li>

                <li>&#10004Auto-Redirect to IDP from login page</li>

                <li>&#10004End to End Provider Configuration</li>

                <li>&#10004Default Attribute Mapping</li>

                <li>&#10004Custom Attribute Mapping</li>

                <li>&#10004Role Mapping</li>

                <li>&#10004Support for multi-store</li>

                <li><s>Support for multisites</s></li>

                <li><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+SAML+Premium+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+SAML+Premium+Plan.+" class="button btn-round">Upgrade Now</a></li>

           </ul>

         </div>
         <div class="columns">

          <ul class="price">

               <li class="header" ';
echo ($this->check_license_plan(3)) ? 'style="background-color: #ea680b"  ' : '';
echo '>Enterprise ';
echo ($this->check_license_plan(3)) ? '<small>' . $version . '</small>' : '';
echo '</li>

               <li class="grey">$599*</li>

               <li>&#10004Auto Create Users (Unlimited)</li>

               <li>&#10004Option to Add SSO login button</li>

               <li>&#10004Options to select SAML Request binding type</li>

               <li>&#10004Unlimited authentication via IDP</li>

               <li>&#10004IDP and SP Initiated SSO</li>

               <li>&#10004Option to select SAML Request</li>

               <li>&#10004SAML Single Logout</li>

               <li>&#10004Auto-Redirect to IDP from login page</li>

               <li>&#10004End to End Provider Configuration</li>

               <li>&#10004Default Attribute Mapping</li>

               <li>&#10004Custom Attribute Mapping</li>

               <li>&#10004Role Mapping</li>

               <li>&#10004Support for multi-store</li>

               <li>&#10004Support for multisites**( 2 subsites)</li>

               <li><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+SAML+Enterprise+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+SAML+Enterprise+Plan.+" class="button btn-round">Upgrade Now</a></li>

            </ul>
            </div>
             </div>
             <div style="margin:2% 0 2% 2%;">

      <form style="display:none;" id="mocf_loginform" action="' . $hostname . '/moas/login"

          target="_blank" method="post">

          <input type="email" name="username" value="' . $email . '" >

          <input type="text" name="redirectUrl" value="' . $hostname . '/moas/initializepayment" >

          <input type="text" name="requestOrigin" id="requestOrigin"  >

      </form>

  </div>

    </div>


  </section>

    </div>

<div>
<p>* Cost applicable for one instance only. Licenses are perpetual and the Support Plan includes 12 months of maintenance (support and version updates). You can renew maintenance after 12 months at 50% of the current license cost.</p><br>

<p>** Multiple Sites Supported
There is an additional cost for the sites if the number of sites is more than 2.</p><br>


<p>Multiple IDPs Supported
We can configure multiple IDPs with our miniOrange cloud. Contact us at <a href="mailto:magentosupport@xecurify.com">magentosupport@xecurify.com</a> for more info.</p><br>


</div>

    ';
