<?php

$fomrKey = $this->getBlockHtml('formkey');
$is_trial_plan = $this->check_license_plan(4) ? 1 : 0;

echo '<div class="login_miniorange">
<div><h3>LOGIN WITH MINIORANGE</h3></div>';

if ($is_trial_plan) {
    print_r('
    <form name="extendtrial" method="post" style="margin-bottom:4%;float:center" action="">
    ' . $fomrKey . '
    <div>
    <input type="hidden" name="option" value="extendTrial">
    <input style="width:18%; text-align:center;height:10%;" type="submit" id="extend_trial" value="Extend Trial" name="submit" class="btn-round extendTrialBtn">
    </form>
    </div>
');
}

echo '
<form id="register_miniorange" name="f" method="post" action="">
        <input type="hidden" name="option" value="loginExistingUser">
        ' . $fomrKey . '
            <hr>
            <br>
            <div id="panel1">
                <div><b>Please Login with your miniOrange credentials</b></div><br>
                <table class="table">
                    <tr>
                    <td><b><font color="#FF0000">*</font>Email:</b></td>
                    <td><input class="" type="email" name="email"  id="loginemail" autofocus="true"
                        required placeholder="person@example.com" style="width:400px;" value=""></td>
                    </tr>
                    <tr>
                    <td><b><font color="#FF0000">*</font>Password:</b></td>
                    <td><input class="" type="password" name="password" style="width:400px;"
                        placeholder="Enter your password" pattern="[a-zA-Z0-9!@#$\.%^&*]{6,24}"></td>
                    </tr>
                </table>
                <br>
                    <td>
                    <input style="width:18%; text-align:center;" type="submit" value="Submit" name="submit" class="btn-round button-align" />

            </div>
        </div>
    </form>
    <br>
    <br/><hr><br/>
    <div><b>Forgot your Password? Use the form below to reset your password.</b></div><br>
    <br>
    <form id="forgot_password" name="f" method="post" action="">
        ' . $fomrKey . '
        <input type="hidden" name="option" value="resetPassword">
        <div class="login_miniorange">
            <table class="table">
                <tr>
                    <td><b><font color="#FF0000">*</font>Email:</b></td>
                    <td><input class="" type="email" name="email"  id="loginemail" autofocus="true"
                        required placeholder="person@example.com" style="width:400px;" value=""></td>
                    <td><input style="width:130%;" type="submit" value="Forgot Password?" class="btn-round"></td>
                </tr>
            </table>
        </div>
    </form>';
